--- #YAML:1.0
name: Class-Prototyped
version: 1.01
author:
  - |-
    Written by Ned Konz, perl@bike-nomad.com and Toby Ovod-Everett, 
    toby@ovod-everett.org. 5.005_03 porting by chromatic.
abstract: Fast prototype-based OO programming in Perl
license: perl
provides:
  Class::Prototyped:
    file: lib/Class/Prototyped.pm
    version: 1.01
  Class::Prototyped::Mirror:
    file: lib/Class/Prototyped.pm
    version: 1.01
  Class::Prototyped::Mirror::Normal:
    file: lib/Class/Prototyped.pm
    version: 1.01
  Class::Prototyped::Mirror::PROFILE:
    file: lib/Class/Prototyped.pm
    version: 1.01
  Class::Prototyped::Mirror::SUPER:
    file: lib/Class/Prototyped.pm
    version: 1.01
  Class::Prototyped::Tied:
    file: lib/Class/Prototyped.pm
    version: 1.01
  Class::Prototyped::Tied::AutoVivify:
    file: lib/Class/Prototyped.pm
    version: 1.01
  Class::Prototyped::Tied::Default:
    file: lib/Class/Prototyped.pm
    version: 1.01
generated_by: Module::Build version 0.24
