---
name: Class-Prototyped
version: 1.11
author:
  - 'Written by Ned Konz, perl@bike-nomad.com and Toby Ovod-Everett, toby@ovod-everett.org. 5.005_03 porting by chromatic.'
abstract: Fast prototype-based OO programming in Perl
license: perl
resources:
  license: http://dev.perl.org/licenses/
provides:
  Class::Prototyped:
    file: lib/Class/Prototyped.pm
    version: 1.11
  Class::Prototyped::Mirror:
    file: lib/Class/Prototyped/Graph.pm
  Class::Prototyped::Mirror::Normal:
    file: lib/Class/Prototyped.pm
  Class::Prototyped::Mirror::PROFILE:
    file: lib/Class/Prototyped.pm
  Class::Prototyped::Mirror::SUPER:
    file: lib/Class/Prototyped.pm
  Class::Prototyped::Tied:
    file: lib/Class/Prototyped.pm
  Class::Prototyped::Tied::AutoVivify:
    file: lib/Class/Prototyped.pm
  Class::Prototyped::Tied::Default:
    file: lib/Class/Prototyped.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
